### ISSUE TITLE
KeyError: images

### ISSUE THREAD

**Issue by Bureda** [TemporAlyx/StreamStableDiffusion#2]
I got it to work, but then I get this error after someone generates:

Traceback (most recent call last):
  File "C:\AIGeneration\stable-diffusion-webui\streambot.py", line 288, in <module>
    main()
  File "C:\AIGeneration\stable-diffusion-webui\streambot.py", line 237, in main
    images, params = check_outputs(Webui_Interface, active_command)
  File "C:\AIGeneration\stable-diffusion-webui\streambot_utils.py", line 188, in check_outputs
    return webui.get_outputs(command)
  File "C:\AIGeneration\stable-diffusion-webui\websocket_interface.py", line 55, in get_outputs
    b64img = resp.json()['images'][0]
KeyError: 'images'

Is it on my end?

**Comment by TemporAlys-dev** [comment]
Looks like the latest version of the webui changed parts of the API, I should be able to push a fix in a few hours.

**Comment by TemporAlys-dev** [comment]
Okay, it does seem like they have changed some things about how the API works that I should look into, 
However, my old way is still seems to work, its just that the --api flag needs to be set in the webui.

So inside of the stable-diffusion-webui directory, 
the webui-user.bat file (or .sh if you are running on linux), 
should be edited to have '--api' to the command line arguments
and look something like this:
![image](https://github.com/TemporAlyx/StreamStableDiffusion/assets/58829937/852201b9-7269-41a6-96bf-0d81fba5be4d)

If I ever get around to rewriting this project hopefully I can make it a little more plug and play, but for now with the --api flag set for the webui it should work correctly.
